from sqlalchemy.orm import declarative_base
from sqlalchemy import String, Text, Boolean, Integer, Column, BigInteger, ARRAY,Float

Base = declarative_base()
    
class Products(Base):
    __tablename__ = 'property'
    url = Column(String)
    description = Column(Text)
    id = Column(String, primary_key=True)
    initial_at = Column(String)
    price = Column(BigInteger)
    price_currency = Column(String)
    price_string = Column(String)
    property_type = Column(String)
    publish_at = Column(String)
    site = Column(String)
    thumbnail = Column(String)
    title = Column(String)
    update_at = Column(String)
    initial_date = Column(String)
    agent_address = Column(String)
    agent_agent_type = Column(String)
    agent_email = Column(String)
    agent_name = Column(String)
    agent_phone_number = Column(String)
    agent_profile = Column(String)
    attr_area = Column(Float)
    attr_bathroom = Column(Integer)
    attr_bedroom = Column(Integer)
    attr_built_year = Column(Integer)
    attr_certificate = Column(String)
    attr_condition = Column(String)
    attr_direction = Column(String)
    attr_feature = Column(String)
    attr_floor = Column(Float)
    attr_floor_num = Column(Float)
    attr_height = Column(Float)
    attr_interior = Column(String)
    attr_length = Column(Float)
    attr_site_id = Column(String)
    attr_total_area = Column(Float)
    attr_total_room = Column(Integer)
    attr_type_detail = Column(String)
    attr_width = Column(Float)
    location_address = Column(String)
    location_city = Column(String)
    location_description = Column(String)
    location_dist = Column(String)
    location_lat = Column(Float)
    location_long = Column(Float)
    location_street = Column(String)
    location_ward = Column(String)
    project_name = Column(String)
    project_profile = Column(String)
    image = Column(Text)