export const propDist = [
  { title: "Tất cả", value: "" },
  { title: "Quận 1", value: "Quận 1" },
  { title: "Quận 2", value: "Quận 2" },
  { title: "Quận 3", value: "Quận 3" },
  { title: "Quận 4", value: "Quận 4" },
  { title: "Quận 5", value: "Quận 5" },
  { title: "Quận 6", value: "Quận 6" },
  { title: "Quận 7", value: "Quận 7" },
  { title: "Quận 8", value: "Quận 8" },
  { title: "Quận 9", value: "Quận 9" },
  { title: "Quận 10", value: "Quận 10" },
  { title: "Quận 11", value: "Quận 11" },
  { title: "Quận 12", value: "Quận 12" },
];

export const propCity = [
  { title: "Tỉnh thành", value: "Tất cả" },
  { title: "Hồ Chí Minh", value: "Thành phố Hồ Chí Minh" },
  { title: "Hà Nội", value: "Thành phố Hà Nội" },
  { title: "Đà Nẵng", value: "Thành phố Đà Nẵng" },
  { title: "Bình Dương", value: "Tỉnh Bình Dương" },
  { title: "An Giang", value: "Tỉnh An Giang" },
  { title: "Bà Rịa Vũng Tàu", value: "Tỉnh Bà Rịa Vũng Tàu" },
  { title: "Bạc Liêu", value: "Tỉnh Bạc Liêu" },
  { title: "Bắc Giang", value: "Tỉnh Bắc Giang" },
  { title: "Bắc Kạn", value: "Tỉnh Bắc Kạn" },
  { title: "Bắc Ninh", value: "Tỉnh Bắc Ninh" },
  { title: "Bến Tre", value: "Tỉnh Bến Tre" },
  { title: "Bình Định", value: "Tỉnh Bình Định" },
  { title: "Bình Phước", value: "Tỉnh Bình Phước" },
  { title: "Bình Thuận", value: "Tỉnh Bình Thuận" },
  { title: "Cà Mau", value: "Tỉnh Cà Mau" },
  { title: "Cao Bằng", value: "Tỉnh Cao Bằng" },
  { title: "Cần Thơ", value: "Thành phố Cần Thơ" },
  { title: "Đắk Lắk", value: "Tỉnh Đắk Lắk" },
  { title: "Đắk Nông", value: "Tỉnh Đắk Nông" },
  { title: "Điện Biên", value: "Tỉnh Điện Biên" },
  { title: "Đồng Nai", value: "Tỉnh Đồng Nai" },
  { title: "Đồng Tháp", value: "Tỉnh Đồng Tháp" },
  { title: "Gia Lai", value: "Tỉnh Gia Lai" },
  { title: "Hà Giang", value: "Tỉnh Hà Giang" },
  { title: "Hà Nam", value: "Tỉnh Hà Nam" },
  { title: "Hà Tĩnh", value: "Tỉnh Hà Tĩnh" },
  { title: "Hải Dương", value: "Tỉnh Hải Dương" },
  { title: "Hải Phòng", value: "Thành phố Hải Phòng" },
  { title: "Hậu Giang", value: "Tỉnh Hậu Giang" },
  { title: "Hòa Bình", value: "Tỉnh Hòa Bình" },
  { title: "Hưng Yên", value: "Tỉnh Hưng Yên" },
  { title: "Kiên Giang", value: "Tỉnh Kiên Giang" },
  { title: "Kon Tum", value: "Tỉnh Kon Tum" },
  { title: "Khánh Hòa", value: "Tỉnh Khánh Hòa" },
  { title: "Lai Châu", value: "Tỉnh Lai Châu" },
  { title: "Lạng Sơn", value: "Tỉnh Lạng Sơn" },
  { title: "Lào Cai", value: "Tỉnh Lào Cai" },
  { title: "Lâm Đồng", value: "Tỉnh Lâm Đồng" },
  { title: "Long An", value: "Tỉnh Long An" },
  { title: "Nam Định", value: "Tỉnh Nam Định" },
  { title: "Ninh Bình", value: "Tỉnh Ninh Bình" },
  { title: "Ninh Thuận", value: "Tỉnh Ninh Thuận" },
  { title: "Nghệ An", value: "Tỉnh Nghệ An" },
  { title: "Phú Thọ", value: "Tỉnh Phú Thọ" },
  { title: "Phú Yên", value: "Tỉnh Phú Yên" },
  { title: "Quảng Bình", value: "Tỉnh Quảng Bình" },
  { title: "Quảng Nam", value: "Tỉnh Quảng Nam" },
  { title: "Quảng Ninh", value: "Tỉnh Quảng Ninh" },
  { title: "Quảng Ngãi", value: "Tỉnh Quảng Ngãi" },
  { title: "Quảng Trị", value: "Tỉnh Quảng Trị" },
  { title: "Sóc Trăng", value: "Tỉnh Sóc Trăng" },
  { title: "Sơn La", value: "Tỉnh Sơn La" },
  { title: "Tây Ninh", value: "Tỉnh Tây Ninh" },
  { title: "Tiền Giang", value: "Tỉnh Tiền Giang" },
  { title: "Tuyên Quang", value: "Tỉnh Tuyên Quang" },
  { title: "Thái Bình", value: "Tỉnh Thái Bình" },
  { title: "Thái Nguyên", value: "Tỉnh Thái Nguyên" },
  { title: "Thanh Hóa", value: "Tỉnh Thanh Hóa" },
  { title: "Thừa Thiên Huế", value: "Tỉnh Thừa Thiên Huế" },
  { title: "Trà Vinh", value: "Tỉnh Trà Vinh" },
  { title: "Vĩnh Long", value: "Tỉnh Vĩnh Long" },
  { title: "Vĩnh Phúc", value: "Tỉnh Vĩnh Phúc" },
  { title: "Yên Bái", value: "Tỉnh Yên Bái" }
];


export const propType = [
  {
    title: "Loại hình",
    value: "",
  },
  {
    title: "Nhà",
    value: "house",
  },
  {
    title: "Đất",
    value: "land",
  },
  {
    title: "Căn hộ",
    value: "apartment",
  }
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];
